language: cpp
cache:
  directories:
    - $HOME/.ccache
addons:
  apt:
    packages:
      - curl
      - ccache
      - build-essential
      - gdb
      - wget
      - debhelper
      - p7zip-full
      - unzip
      - flex
      - bison
      - libsdl1.2-dev
      - libudev-dev
      - libusb-1.0-0-dev
      - libc6-i386
#  artifacts:
#      paths:
#        - $(ls ./build/*.deb | tr "\n" ":")
#        - $(ls ./build/*.dmg | tr "\n" ":")
#        - $(ls ./build/*.exe | tr "\n" ":")
os:
  - linux
  - osx
env:

install: make arm_sdk_install && make qt_sdk_install && make gtest_install && make CCACHE=ccache config_new
script: make all_ut_run && make all_fw -j4 && make package -j4
#notifications:
#  email:
