/**
 ******************************************************************************
 * @addtogroup OpenPilotModules OpenPilot Modules
 * @{
 * @addtogroup LineSensorModule Module
 * @brief      Module to read a line sensor.
 * Updates the FlightBatteryState object
 * @{
 *
 * @file       linesensormodule.c
 * @author     The LibrePilot Project, http://www.librepilot.org Copyright (C) 2015-2016.
 * @brief      Module to read a line sensor.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

/**
 * Output object: FlightBatteryState
 *
 * This module will periodically generate information on the battery state.
 *
 * UAVObjects are automatically generated by the UAVObjectGenerator from
 * the object definition XML file.
 *
 * Modules have no API, all communication to other modules is done through UAVObjects.
 * However modules may use the API exposed by shared libraries.
 * See the OpenPilot wiki for more details.
 * http://www.openpilot.org/OpenPilot_Application_Architecture
 *
 */

#include "openpilot.h"
#include "linesensor.h"
//
// Configuration
//
#define SAMPLE_PERIOD_MS 5
// Private types

// Private variables

static const int8_t analogSensorPins[] = { 2, 3, 4, 5 }; // ADC pin for voltage
static const int8_t analogSensorPos[] = { 2, 3, 4, 5 }; // ADC pin for voltage
static int8_t analogSensorCount = NELEMENTS(analogSensorPins);

// Private functions
static void onTimer(UAVObjEvent *ev);

/**
 * Initialise the module, called on startup
 * \returns 0 on success or -1 if initialisation failed
 */
int32_t LineSensorModuleInitialize(void)
{
        LineSensorInitialize();

        static UAVObjEvent ev;

        memset(&ev, 0, sizeof(UAVObjEvent));
        EventPeriodicCallbackCreate(&ev, onTimer, SAMPLE_PERIOD_MS / portTICK_RATE_MS);
    return 0;
}


MODULE_INITCALL(LineSensorModuleInitialize, 0);
static void onTimer(__attribute__((unused)) UAVObjEvent *ev)
{
    static LineSensorData sensorData;

    for(uint8_t i = 0; i < analogSensorCount; i++){
        sensorData.sensors[analogSensorPos[i]] = (int16_t) (PIOS_ADC_PinGetVolt(analogSensorPins[i]) * 10000.0f);
    }
    sensorData.sensors[0]++;
    // ad a plausibility check: zero voltage => zero current
    LineSensorSet(&sensorData);
}

/**
 * @}
 */

/**
 * @}
 */
